### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by simcha-c** [joedspin/bandramp#2]
Hello,

Great job on the schema! Looks like you put a lot of time thinking about what needs to go where and I can also tell you have experience with music. :) Here are some notes/questions about your tables.

1. Let's put the `artists` table before the `albums` table since `albums` reference `artists` with the `artist_id`.

**albums table:**

2. Let's take out the `price`, `tags` and `published_state` from this table. These are bonus / bonus-bonus features that will come later on, so you would want to add that to the tables when you start working on those features.
3. What is `credits`, `upc_ean`, and `catalog_number`? I'm trying to find that on the albums page, but i cant find it anywhere...

**artists table:** 

4. is an artist a user? Do we need a foreign key of user_id for each artist? How does that work?
5. what do you mean when the artist `name` is unique? Can two artists not have the same name? if so, artist table looks great!

**tracks table:** 

6. Since the `albums` table has the `artist_id` on it, we don't need to include that here. That could be a through association that we make connecting the tracks to artists through albums.
7. Where do we see lyrics for a track on bandcamp? I don't see it anywhere...
8. Again, let's take out `price`. and what is `credits` and `license_id`?
9. What is `featured`?

**general:**

10. Let's take out these tables: `published_states`, `licenses `, `articles`, and `wishlist`. Let's put `follows` as a bonus table.
11. `genres` and `genres_joins` tables is a really cool idea. Especially for searching by a certain genre... can a artist have a certain genre on them too? or can an album have songs with different genres? How do genres work?

`follows` table looks great!

Best,
Simcha

**Comment by joedspin** [comment]
Hi Simcha,

Thank you for this feedback. It's very helpful. I'm working on updating the schema to incorporate your guidance. I have a few questions / responses:

**albums table:**
1) upc_ean is the bar code for the product. not all albums have them, but it is standard data that would be tracked with an album. Catalog number is more or less the same, but it's not an officially registered barcode, it's usually just a sequencing number used by labels to catalog their releases. 
2) published_state allows an album to be in draft status until you're finished uploading all the details. After your done you publish it and it becomes visible on the front end. Do you think it makes sense to maintain this workflow? I could simplify it and just make it a boolean (on bandcamp the options are Published, Private, or Draft).
3) I took out credits and about and just left in the description field. All pertinent info can be kept there for the purposes of this clone.
4) Added an img_url field for albums

**artists table**
1. ) Artists and users make sense to be in different tables. Not all users are artists and a user might be one member of a band and the Band would be the artist name instead of the user who is managing their page. However, if for the sake of the demo and in keeping with what previous cloners have done it is simpler to merge those two tables, I can understand the reason for it. I would then add an artist name field to the users table because right now we don't have any forward-facing name for the artist within the users table. It does make sense to have a link to user via an admin_user_id field so we know who created and manages an artist.
2.) I guess you're right that it should be possible for more than one artist to have the same name, so I'll remove the unique requirement on that field.
3. Added an img_url field for artists. This is used as the header on all their album pages.

**tracks table**
1) Bandcamp does have a field for artist on each track. This would override or supplement the artist defined on a whole album, this is why I included artist_id in the tracks table as well. But for the sake of this clone, I'll remove it.
2.) Like in albums, credits is an optional field so you won't see it on all listings. I'll remove it for the clone.
3.) "featured" indicates which track is loaded with a play button at the top of the album page by default. It would be just as easy in this clone to always use the first track. Bandcamp allows you to specify one other than the first one.
4.) Lyrics are a clickable link next to each track on the album. This is a very cool feature that should be easy to implement.
5.) Added a field for track duration - this is a prominent data point on the album pages and is needed to make the clone look like the real thing.

**genres table**
1) Yes, artists and tracks should also be able to have genres specified on them. So that would be two more join tables I guess. Or would it be better to have a join table that could like either an artist, album, or track to a genres and have a field that defines which type of association it is?

I hope my responses are not too lengthy.

Best,

Joe

**Comment by simcha-c** [comment]
polymorphic association

genres table
id 
name

albums table
id
info

tracks table
id
info

join(call it something else)
id
genre
receiver_id
receiver_type ['tracks', albums']

**Comment by simcha-c** [comment]
**albums table**
- [x] `artist name` and `releasedDate` should be snake_cased. Also, there's an extra period by the `published` column.
- [x] I think it would make sense for `release_date` to have a not null constraint.
- [ ] in the bullet points, the last 2 are referencing columns that don't exist anymore.

**tracks table**
- [x] `releaseDate` should be snake_cased.

**featured tracks**
- [x] this would not work if two tracks on an album have featured as true. I think we need a separate table for this that has uniqueness on the combo of `album_id` and `track_id`.
- [x] bullet points reference outdated schema.
- [x] I see that you wrote in your bullet points, 'enforce only one featured track per album'. That would be possible with what i was describing above with a `features` table.

**genre joins**
- [x] let's call this table `genre_assignments`.
- [x] column `item_table` should be called `item_type`. That is the convention for polymorphic associations.
- [x]  maybe instead of `item` it should be `assignment_type` and `assignment_id`.


Really great job!
Simcha

**Comment by joedspin** [comment]
**tracks table**
Decided to always use the first track as the featured track for the purposes of the demo. It's an unnecessary level of complication to allow the user to specify a different track.

**Comment by simcha-c** [comment]
sounds good!
